# Esse arquivo foi generado por mim
# https://github.com/firebase/firebase-tools

name: Testar app quando dar push na `test`
'on': 
  push:
    branches:
      - test
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CASTELANARTBR }}'
          channelId: ''
          projectId: castelanartbr
